## Постановка задачи
Необходимо рассчитать следующие метрики:
- leave to start ratio - коэффициент соотношения покинувших пользовтелей сайт к тем, кто начал участие
- days to churn - время с последнего действия на сайте до момента ухода

## Данные 
Данные представлены с трех независимых источников и состоят из следующих признаков:
- Unnamed: 0 - ID строки
- topic_id - идентификационный номер топика. Топик состоит из одного вопроса и всех ответов  к нему
- id — идентификационный номер поста
- parent_id — идентификационный номер родительского поста для ответов или -1 для вопросов
- post_type — тип поста. Посты бывают только двух типов: вопрос — 1, ответ — 2.
- created_at — дата создания публикации
- author_id — идентификационный номер автора поста
- post_count - количество постов в вопросе
- view_count - количество просмотров
- reply_time - время ответа
- is_accepted_answer - ответ на вопрос?
- author_username - имя пользователя

## Как определять последнее действие пользователя?

Способ 1 - Последнее действие выбирается исходя из даты последнего зарегистрированного в БД

Способ 2 - Использовать модель Customer Livetime Value, через вероятность.

Загружаем библиотеки

In [165]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
from pymc_marketing.clv import ParetoNBDModel
from pymc_marketing.clv.utils import rfm_summary
import seaborn as sns
import arviz as az
import os


sns.set(style="darkgrid")

Загружаем датасет и смотрим на признаки

In [166]:
elastic = pd.read_csv(r'..\data\raw_data\elastic.csv')
freecodecamp = pd.read_csv(r'..\data\raw_data\freecodecamp.csv')
pythoncom = pd.read_csv(r'..\data\raw_data\python.csv')
datas = {
    'elastic': elastic,
    'freecodecamp': freecodecamp,
    'python': pythoncom
}

In [167]:
elastic[elastic['author_id'] <= -2].head()

,Unnamed: 0,topic_id,id,parent_id,post_type,posts_count,view_count,created_at,reply_time,is_accepted_answer,author_id,author_username
232546,232546,346432,1333928,1333871,2,0,0,2023-11-04 21:13:31.488000+00:00,0.4,False,-2,discobot

In [168]:
freecodecamp[freecodecamp['author_id'] <= -0].head()

,Unnamed: 0,topic_id,id,parent_id,post_type,posts_count,view_count,created_at,reply_time,is_accepted_answer,author_id,author_username
4,4,636351,1882964,1760497,2,0,0,2024-03-09 01:04:07.581000+00:00,182.53,False,-1,system
9,9,636343,1882965,1760483,2,0,0,2024-03-09 01:07:07.352000+00:00,182.56,False,-1,system
13,13,636329,1882967,1760452,2,0,0,2024-03-09 01:11:06.063000+00:00,182.60,False,-1,system
18,18,636366,1882971,1760537,2,0,0,2024-03-09 01:19:07.071000+00:00,182.51,False,-1,system
24,24,636331,1882977,1760455,2,0,0,2024-03-09 01:23:03.098000+00:00,182.60,False,-1,system

In [169]:
pythoncom[pythoncom['author_id'] <= -1].head()

,Unnamed: 0,topic_id,id,parent_id,post_type,posts_count,view_count,created_at,reply_time,is_accepted_answer,author_id,author_username
1828,1828,18844,114046,66593,2,0,0,2023-09-07 13:00:06.402000+00:00,365.0,False,-1,system
2253,2253,18988,114958,67116,2,0,0,2023-09-12 11:22:34.476000+00:00,365.0,False,-1,system
2658,2658,21087,127460,74589,2,0,0,2023-11-15 12:51:01.256000+00:00,365.0,False,-1,system
3062,3062,19599,118528,69309,2,0,0,2023-09-30 17:54:43.405000+00:00,365.0,False,-1,system
4088,4088,24059,147657,86468,2,0,0,2024-02-21 00:20:53.997000+00:00,365.0,False,-1,system

In [170]:
elastic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366549 entries, 0 to 366548
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Unnamed: 0          366549 non-null  int64
 1   topic_id            366549 non-null  int64
 2   id                  366549 non-null  int64
 3   parent_id           366549 non-null  int64
 4   post_type           366549 non-null  int64
 5   posts_count         366549 non-null  int64
 6   view_count          366549 non-null  int64
 7   created_at          366549 non-null  object
 8   reply_time          366549 non-null  float64
 9   is_accepted_answer  366549 non-null  bool
 10  author_id           366549 non-null  int64
 11  author_username     366549 non-null  object
dtypes: bool(1), float64(1), int64(8), object(2)
memory usage: 31.1+ MB

In [171]:
freecodecamp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351988 entries, 0 to 351987
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Unnamed: 0          351988 non-null  int64
 1   topic_id            351988 non-null  int64
 2   id                  351988 non-null  int64
 3   parent_id           351988 non-null  int64
 4   post_type           351988 non-null  int64
 5   posts_count         351988 non-null  int64
 6   view_count          351988 non-null  int64
 7   created_at          351988 non-null  object
 8   reply_time          351988 non-null  float64
 9   is_accepted_answer  351988 non-null  bool
 10  author_id           351988 non-null  int64
 11  author_username     351988 non-null  object
dtypes: bool(1), float64(1), int64(8), object(2)
memory usage: 29.9+ MB

In [172]:
pythoncom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135409 entries, 0 to 135408
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Unnamed: 0          135409 non-null  int64
 1   topic_id            135409 non-null  int64
 2   id                  135409 non-null  int64
 3   parent_id           135409 non-null  int64
 4   post_type           135409 non-null  int64
 5   posts_count         135409 non-null  int64
 6   view_count          135409 non-null  int64
 7   created_at          135409 non-null  object
 8   reply_time          135409 non-null  float64
 9   is_accepted_answer  135409 non-null  bool
 10  author_id           135409 non-null  int64
 11  author_username     135408 non-null  object
dtypes: bool(1), float64(1), int64(8), object(2)
memory usage: 11.5+ MB

В каждом из датасете есть есть строчки относящиеся к пользователю system и discobot, поэтому убираем их (они являются выбросом по количеству сообщений)

In [173]:
for name, data in datas.items():
    print(f'Очищаем данные для датасета {name}...')
    data.drop(data[data['author_id'] < 0].index, inplace=True)
    print(f'Строчки с пользователями system и discobot убраны для датасета {name}\nПереводим столбец created_at в формат datetime')
    data['created_at'] = pd.to_datetime(data['created_at'], format='mixed', errors='coerce')

Очищаем данные для датасета elastic...
Строчки с пользователями system и discobot убраны для датасета elastic
Переводим столбец created_at в формат datetime
Очищаем данные для датасета freecodecamp...
Строчки с пользователями system и discobot убраны для датасета freecodecamp
Переводим столбец created_at в формат datetime
Очищаем данные для датасета python...
Строчки с пользователями system и discobot убраны для датасета python
Переводим столбец created_at в формат datetime

## Переходим к расчету наших метрик:
Для работы нам необходимо подготовить датафрейм, в котором будет выполнена агрегация по юзеру, где указано первое и последнее действие в сообществе и общее количество сообщений в течении lifetime

In [174]:
def leave_to_start_ratio_by_last_action(data):

    data = data.copy()
    
    print(f'Переводим время в формат datetime')

    data['created_at'] = pd.to_datetime(data['created_at']).dt.to_period('D')

    print(f'Выполняем агрегацию по юзеру')

    data_user_agg = data.groupby('author_id')['created_at'].agg(['min', 'max']).reset_index() #агрегируем пользователя и получаем время первого и последнего сообщения, а также общее количнство
    data_user_agg.columns = ['author_id', 'first_action', 'last_action']

    print(f'Агрегацию по пользователя прошла успешно\nПереходим к созданию временной шкалы')

    all_days = pd.period_range(
        start = data_user_agg['first_action'].min(),
        end = data_user_agg['first_action'].max(),
        freq = 'D'
    )

    print(f'Собираем информацию по ушедшим и пришедшим юзерам в течении дня')

    count_users_start = data_user_agg.groupby('first_action').size().reindex(all_days, fill_value=0) #количество новых пользователйе 
    count_users_leave = data_user_agg.groupby('last_action').size().reindex(all_days, fill_value=0) #количество ушедших пользлователей
    
    print(f'Создаем датафрейм для метрик')

    data_metrics = pd.DataFrame({
        'Новые юзеры': count_users_start,
        'Ушедшие юзеры по последнему действию': count_users_leave
    })

    print(f'Считаем коэффициент leave to start ratio')

    data_metrics['Коэффициент leave_to_start по последнему действию'] = (data_metrics['Ушедшие юзеры по последнему действию'] / data_metrics['Новые юзеры']).fillna(0)
    data_metrics['Нетто изменение по последнему действию'] = data_metrics['Новые юзеры'] - data_metrics['Ушедшие юзеры по последнему действию']

    return data_metrics

metrics_dict = {}
for name, data in datas.items():
        data_metrics_by_last_action = leave_to_start_ratio_by_last_action(data)
        metrics_dict[f'{name}_metrics_by_last_action'] = data_metrics_by_last_action
        print(f'Набор данных: {name}')
        print(data_metrics_by_last_action.head(2))
        print("-" * 60)

Переводим время в формат datetime
Выполняем агрегацию по юзеру
Агрегацию по пользователя прошла успешно
Переходим к созданию временной шкалы
Собираем информацию по ушедшим и пришедшим юзерам в течении дня
Создаем датафрейм для метрик
Считаем коэффициент leave to start ratio
Набор данных: elastic
            Новые юзеры  Ушедшие юзеры по последнему действию  \
2010-07-29            2                                     1
2010-07-30            0                                     0

            Коэффициент leave_to_start по последнему действию  \
2010-07-29                                                0.5
2010-07-30                                                0.0

            Нетто изменение по последнему действию
2010-07-29                                       1
2010-07-30                                       0
------------------------------------------------------------
Переводим время в формат datetime
Выполняем агрегацию по юзеру
Агрегацию по пользователя прошла успешно
Переходим к созданию временной шкалы
Собираем информацию по ушедшим и пришедшим юзерам в течении дня
Создаем датафрейм для метрик
Считаем коэффициент leave to start ratio
Набор данных: freecodecamp
            Новые юзеры  Ушедшие юзеры по последнему действию  \
2016-05-12            3                                     1
2016-05-13            0                                     0

            Коэффициент leave_to_start по последнему действию  \
2016-05-12                                           0.333333
2016-05-13                                           0.000000

            Нетто изменение по последнему действию
2016-05-12                                       2
2016-05-13                                       0
------------------------------------------------------------
Переводим время в формат datetime
Выполняем агрегацию по юзеру
Агрегацию по пользователя прошла успешно
Переходим к созданию временной шкалы
Собираем информацию по ушедшим и пришедшим юзерам в течении дня
Создаем датафрейм для метрик
Считаем коэффициент leave to start ratio
Набор данных: python
            Новые юзеры  Ушедшие юзеры по последнему действию  \
2018-09-28            7                                     0
2018-09-29           14                                     0

            Коэффициент leave_to_start по последнему действию  \
2018-09-28                                                0.0
2018-09-29                                                0.0

            Нетто изменение по последнему действию
2018-09-28                                       7
2018-09-29                                      14
------------------------------------------------------------

C:\Users\klyko\AppData\Local\Temp\ipykernel_18652\1199310614.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  data['created_at'] = pd.to_datetime(data['created_at']).dt.to_period('D')
C:\Users\klyko\AppData\Local\Temp\ipykernel_18652\1199310614.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  data['created_at'] = pd.to_datetime(data['created_at']).dt.to_period('D')
C:\Users\klyko\AppData\Local\Temp\ipykernel_18652\1199310614.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  data['created_at'] = pd.to_datetime(data['created_at']).dt.to_period('D')

In [175]:
metrics_dict.keys()

dict_keys(['elastic_metrics_by_last_action', 'freecodecamp_metrics_by_last_action', 'python_metrics_by_last_action'])

In [176]:
os.makedirs("..\models", exist_ok=True)

In [177]:
#Функция будет возвращать два датафрейма
def leave_to_start_ratio_by_clv_model(data, name, b=0.5): #b - вероятность с которой считается пользователь ушедшим
    data = data.copy()

    print(f'Создаем новый датафрейм rfm сводку')

    data = data[['author_id', 'created_at']]
    

    rfm = rfm_summary(
        data,
        'author_id',
        'created_at'
    )

    rfm.to_csv(f"..\models\{name}_rfm.csv", index=False)
    
    print(f'RFM сводка успешно создана и переходим к обучению модели CLV')

    model = ParetoNBDModel(data=rfm)
    model.build_model()
    model.fit(fit_method='map')

    # Сохраняем обученную модель (InferenceData)
    model_path = f"..\models\{name}_pareto_nbd_model.nc"
    az.to_netcdf(model.idata, model_path)

    print(f'Модель обучена - считаем вероятности ухода')

    p_alive = model.expected_probability_alive()
    p_alive_clean = p_alive.squeeze()
    p_alive_values = p_alive_clean.values.ravel()

    rfm['Вероятность, что юзер живой'] = p_alive_values
    rfm['is_churn'] = rfm['Вероятность, что юзер живой'] < b

    print(f'агрегируем по пользователю и сохраняем первое и последнее время активности')
    
    data['created_at'] = pd.to_datetime(data['created_at']).dt.to_period('D')
    data_user_agg = data.groupby('author_id')['created_at'].agg(['min', 'max']).reset_index()
    data_user_agg.columns = ['customer_id', 'first_action', 'last_action']

    all_days = pd.period_range(
        start = data_user_agg['first_action'].min(),
        end = data_user_agg['first_action'].max(),
        freq = 'D'
    )

    print(f'Создаем сводную таблицу. Join по customer id')

    data_user_agg = rfm.merge(
        data_user_agg[['customer_id', 'first_action', 'last_action']],
        on = 'customer_id',
        how = 'left'
    )

    data_user_agg['Расчетное время ухода юзера (churn date)'] = np.where(
        data_user_agg['is_churn'],
        data_user_agg['last_action'],
        pd.NaT
    )

    data_user_agg['Последняя запись юзера в БД'] = data_user_agg['last_action'] #даем более читаемое название
    data_user_agg.drop(columns=['last_action'], inplace=True)
    
    churn = data_user_agg.groupby('Расчетное время ухода юзера (churn date)').size().reindex(all_days, fill_value=0)
    count_users_start = data_user_agg.groupby('first_action').size().reindex(all_days, fill_value=0) #количество новых пользователйе 
    
    data_metrics = pd.DataFrame(index=all_days)
    data_metrics['Ушедшие юзеры по модели CLV'] = churn
    data_metrics['Новые юзеры'] = count_users_start
    data_metrics['Коэффициент leave_to_start по модели CLV'] = (
        data_metrics['Ушедшие юзеры по модели CLV'] /
        data_metrics['Новые юзеры']
    ).replace([np.inf, -np.inf], np.nan).fillna(0)
    data_metrics['Нетто изменение по CLV модели'] = data_metrics['Новые юзеры'] - data_metrics['Ушедшие юзеры по модели CLV']

    data_user_agg.to_csv(f"..\models\{name}_data_user_agg.csv", index=False)

    return data_metrics

for name, data in datas.items():
        data_metrics_by_clv_model = leave_to_start_ratio_by_clv_model(data, name)
        metrics_dict[f'{name}_metrics_by_clv_model'] = data_metrics_by_clv_model #сохраняем метрики по мдели
        
        print(f'Набор данных: {name}')
        print(data_metrics_by_clv_model.head(2))
        print("-" * 60)

Создаем новый датафрейм rfm сводку

c:\Users\klyko\.conda\envs\community_management\lib\site-packages\pymc_marketing\clv\utils.py:340: UserWarning: Converting to Period representation will drop timezone information.
  .to_period(time_unit)
c:\Users\klyko\.conda\envs\community_management\lib\site-packages\pymc_marketing\clv\utils.py:226: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  transactions.set_index(datetime_col).to_period(time_unit).to_timestamp()

RFM сводка успешно создана и переходим к обучению модели CLV

Output()

Модель обучена - считаем вероятности ухода
агрегируем по пользователю и сохраняем первое и последнее время активности

C:\Users\klyko\AppData\Local\Temp\ipykernel_18652\275162877.py:39: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  data['created_at'] = pd.to_datetime(data['created_at']).dt.to_period('D')

Создаем сводную таблицу. Join по customer id
Набор данных: elastic
            Ушедшие юзеры по модели CLV  Новые юзеры  \
2010-07-29                            1            2
2010-07-30                            0            0

            Коэффициент leave_to_start по модели CLV  \
2010-07-29                                       0.5
2010-07-30                                       0.0

            Нетто изменение по CLV модели
2010-07-29                              1
2010-07-30                              0
------------------------------------------------------------
Создаем новый датафрейм rfm сводку

c:\Users\klyko\.conda\envs\community_management\lib\site-packages\pymc_marketing\clv\utils.py:340: UserWarning: Converting to Period representation will drop timezone information.
  .to_period(time_unit)
c:\Users\klyko\.conda\envs\community_management\lib\site-packages\pymc_marketing\clv\utils.py:226: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  transactions.set_index(datetime_col).to_period(time_unit).to_timestamp()

RFM сводка успешно создана и переходим к обучению модели CLV

Output()

Модель обучена - считаем вероятности ухода
агрегируем по пользователю и сохраняем первое и последнее время активности
Создаем сводную таблицу. Join по customer id

C:\Users\klyko\AppData\Local\Temp\ipykernel_18652\275162877.py:39: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  data['created_at'] = pd.to_datetime(data['created_at']).dt.to_period('D')

Набор данных: freecodecamp
            Ушедшие юзеры по модели CLV  Новые юзеры  \
2016-05-12                            1            3
2016-05-13                            0            0

            Коэффициент leave_to_start по модели CLV  \
2016-05-12                                  0.333333
2016-05-13                                  0.000000

            Нетто изменение по CLV модели
2016-05-12                              2
2016-05-13                              0
------------------------------------------------------------
Создаем новый датафрейм rfm сводку
RFM сводка успешно создана и переходим к обучению модели CLV

c:\Users\klyko\.conda\envs\community_management\lib\site-packages\pymc_marketing\clv\utils.py:340: UserWarning: Converting to Period representation will drop timezone information.
  .to_period(time_unit)
c:\Users\klyko\.conda\envs\community_management\lib\site-packages\pymc_marketing\clv\utils.py:226: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  transactions.set_index(datetime_col).to_period(time_unit).to_timestamp()

Output()

Модель обучена - считаем вероятности ухода
агрегируем по пользователю и сохраняем первое и последнее время активности
Создаем сводную таблицу. Join по customer id
Набор данных: python
            Ушедшие юзеры по модели CLV  Новые юзеры  \
2018-09-28                            0            7
2018-09-29                            0           14

            Коэффициент leave_to_start по модели CLV  \
2018-09-28                                       0.0
2018-09-29                                       0.0

            Нетто изменение по CLV модели
2018-09-28                              7
2018-09-29                             14
------------------------------------------------------------

C:\Users\klyko\AppData\Local\Temp\ipykernel_18652\275162877.py:39: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  data['created_at'] = pd.to_datetime(data['created_at']).dt.to_period('D')

In [178]:
metrics_dict.keys()

dict_keys(['elastic_metrics_by_last_action', 'freecodecamp_metrics_by_last_action', 'python_metrics_by_last_action', 'elastic_metrics_by_clv_model', 'freecodecamp_metrics_by_clv_model', 'python_metrics_by_clv_model'])

In [181]:
(pd.read_csv(f'..\models\elastic_data_user_agg.csv')).head()

,customer_id,frequency,recency,T,"Вероятность, что юзер живой",is_churn,first_action,Расчетное время ухода юзера (churn date),Последняя запись юзера в БД
0,2,16.0,716.0,3542.0,4.246763e-11,True,2015-06-15,2017-05-31,2017-05-31
1,5,45.0,3303.0,3584.0,6.616259e-01,False,2015-05-04,NaN,2024-05-19
2,7,12.0,485.0,3500.0,1.389963e-10,True,2015-07-27,2016-11-23,2016-11-23
3,8,1.0,90.0,3532.0,1.432838e-03,True,2015-06-25,2015-09-23,2015-09-23
4,10,7.0,56.0,3588.0,9.019784e-14,True,2015-04-30,2015-06-25,2015-06-25

In [184]:

def predict_churn_date(name, b=0.5):

    print(f'Загружаем модель и данные для набора {name}')
    idata = az.from_netcdf(f"..\models\{name}_pareto_nbd_model.nc")
    rfm = pd.read_csv(f'..\models\{name}_rfm.csv')
    model = ParetoNBDModel(data=rfm)
    model.build_model()
    model.idata = idata

    print(f'Оставляем тех, для кого на последнюю запись в БД модель выдает вероятность быть живым больше {b}')

    data_user_agg = pd.read_csv(f"..\models\{name}_data_user_agg.csv")
    data_user_agg['Последняя запись юзера в БД'] = pd.to_datetime(
         data_user_agg['Последняя запись юзера в БД'], format = 'mixed', errors='coerce')
    churn_users = data_user_agg.loc[data_user_agg['is_churn'], 'customer_id'].tolist()
    data_user_agg_predict = data_user_agg[~data_user_agg['customer_id'].isin(churn_users)].copy()

    active_users = data_user_agg_predict['customer_id'].tolist()

    days_forward = 0
    horizon = 365

    while len(active_users) > 0 and days_forward < horizon:
        days_forward += 1
        print(f"День {days_forward}: осталось пользователей {len(active_users)}")

        # Увеличиваем время наблюдения Т на 1 день
        data_user_agg_predict.loc[data_user_agg_predict['customer_id'].isin(active_users), 'T'] += 1

        #Рассчитываем вероятность быть живым для активных пользователей

        p_alive = model.expected_probability_alive(data_user_agg_predict)
        p_alive_clean = p_alive.squeeze()
        p_alive_values = p_alive_clean.values.ravel()
        data_user_agg_predict['Вероятность, что юзер живой'] = p_alive_values

        churn_that_day = data_user_agg_predict[
            (data_user_agg_predict['customer_id'].isin(active_users)) &
            (data_user_agg_predict['Вероятность, что юзер живой'] < b)
        ]

        mask = data_user_agg_predict['customer_id'].isin(churn_that_day['customer_id'])
        data_user_agg_predict.loc[
            mask,
            'Расчетное время ухода юзера (churn date)'
        ] = (
            data_user_agg_predict.loc[mask, 'Последняя запись юзера в БД']
            + pd.to_timedelta(days_forward, unit='D')
        )
        
        active_users = list(
            set(active_users) -
            set(churn_that_day['customer_id'])
        )

    data_user_agg = data_user_agg.merge(
        data_user_agg_predict[['customer_id', 'Расчетное время ухода юзера (churn date)']],
        on='customer_id',
        how='left'
    )

    return data_user_agg

for name, data in datas.items():
        data_user_agg_predicted = predict_churn_date(name)
        metrics_dict[f'{name}_lifetime_predicted'] = data_user_agg_predicted #сохраняем метрики по мдели
        
        print(f'Набор данных: {name}')
        print(data_user_agg_predicted.head(2))
        print("-" * 60)

Загружаем модель и данные для набора elastic
Оставляем тех, для кого на последнюю запись в БД модель выдает вероятность быть живым больше 0.5
День 1: осталось пользователей 1468
День 2: осталось пользователей 1451
День 3: осталось пользователей 1435
День 4: осталось пользователей 1426
День 5: осталось пользователей 1417
День 6: осталось пользователей 1404
День 7: осталось пользователей 1390
День 8: осталось пользователей 1373
День 9: осталось пользователей 1362
День 10: осталось пользователей 1353
День 11: осталось пользователей 1345
День 12: осталось пользователей 1328
День 13: осталось пользователей 1303
День 14: осталось пользователей 1298
День 15: осталось пользователей 1293
День 16: осталось пользователей 1289
День 17: осталось пользователей 1278
День 18: осталось пользователей 1276
День 19: осталось пользователей 1270
День 20: осталось пользователей 1264
День 21: осталось пользователей 1261
День 22: осталось пользователей 1246
День 23: осталось пользователей 1239
День 24: осталось пользователей 1235
День 25: осталось пользователей 1230
День 26: осталось пользователей 1224
День 27: осталось пользователей 1220
День 28: осталось пользователей 1213
День 29: осталось пользователей 1205
День 30: осталось пользователей 1199
День 31: осталось пользователей 1196
День 32: осталось пользователей 1192
День 33: осталось пользователей 1186
День 34: осталось пользователей 1179
День 35: осталось пользователей 1173
День 36: осталось пользователей 1166
День 37: осталось пользователей 1161
День 38: осталось пользователей 1154
День 39: осталось пользователей 1150
День 40: осталось пользователей 1141
День 41: осталось пользователей 1136
День 42: осталось пользователей 1135
День 43: осталось пользователей 1133
День 44: осталось пользователей 1126
День 45: осталось пользователей 1121
День 46: осталось пользователей 1116
День 47: осталось пользователей 1108
День 48: осталось пользователей 1102
День 49: осталось пользователей 1095
День 50: осталось пользователей 1090
День 51: осталось пользователей 1088
День 52: осталось пользователей 1083
День 53: осталось пользователей 1080
День 54: осталось пользователей 1077
День 55: осталось пользователей 1073
День 56: осталось пользователей 1069
День 57: осталось пользователей 1063
День 58: осталось пользователей 1058
День 59: осталось пользователей 1055
День 60: осталось пользователей 1049
День 61: осталось пользователей 1045
День 62: осталось пользователей 1035
День 63: осталось пользователей 1031
День 64: осталось пользователей 1026
День 65: осталось пользователей 1021
День 66: осталось пользователей 1016
День 67: осталось пользователей 1009
День 68: осталось пользователей 1006
День 69: осталось пользователей 1000
День 70: осталось пользователей 998
День 71: осталось пользователей 992
День 72: осталось пользователей 989
День 73: осталось пользователей 985
День 74: осталось пользователей 983
День 75: осталось пользователей 977
День 76: осталось пользователей 975
День 77: осталось пользователей 971
День 78: осталось пользователей 967
День 79: осталось пользователей 966
День 80: осталось пользователей 959
День 81: осталось пользователей 957
День 82: осталось пользователей 954
День 83: осталось пользователей 950
День 84: осталось пользователей 947
День 85: осталось пользователей 940
День 86: осталось пользователей 938
День 87: осталось пользователей 936
День 88: осталось пользователей 931
День 89: осталось пользователей 928
День 90: осталось пользователей 923
День 91: осталось пользователей 918
День 92: осталось пользователей 917
День 93: осталось пользователей 915
День 94: осталось пользователей 911
День 95: осталось пользователей 907
День 96: осталось пользователей 905
День 97: осталось пользователей 900
День 98: осталось пользователей 899
День 99: осталось пользователей 898
День 100: осталось пользователей 896
День 101: осталось пользователей 892
День 102: осталось пользователей 890
День 103: осталось пользователей 882
День 104: осталось пользователей 878
День 105: осталось пользователей 873
День 106: осталось пользователей 870
День 107: осталось пользователей 868
День 108: осталось пользователей 866
День 109: осталось пользователей 865
День 110: осталось пользователей 862
День 111: осталось пользователей 860
День 112: осталось пользователей 857
День 113: осталось пользователей 855
День 114: осталось пользователей 853
День 115: осталось пользователей 849
День 116: осталось пользователей 846
День 117: осталось пользователей 842
День 118: осталось пользователей 840
День 119: осталось пользователей 834
День 120: осталось пользователей 831
День 121: осталось пользователей 829
День 122: осталось пользователей 827
День 123: осталось пользователей 825
День 124: осталось пользователей 824
День 125: осталось пользователей 820
День 126: осталось пользователей 817
День 127: осталось пользователей 816
День 128: осталось пользователей 812
День 129: осталось пользователей 811
День 130: осталось пользователей 809
День 131: осталось пользователей 803
День 132: осталось пользователей 798
День 133: осталось пользователей 797
День 134: осталось пользователей 793
День 135: осталось пользователей 792
День 136: осталось пользователей 788
День 137: осталось пользователей 783
День 138: осталось пользователей 778
День 139: осталось пользователей 776
День 140: осталось пользователей 775
День 141: осталось пользователей 770
День 142: осталось пользователей 769
День 143: осталось пользователей 766
День 144: осталось пользователей 763
День 145: осталось пользователей 759
День 146: осталось пользователей 758
День 147: осталось пользователей 757
День 148: осталось пользователей 749
День 149: осталось пользователей 747
День 150: осталось пользователей 746
День 151: осталось пользователей 740
День 152: осталось пользователей 737
День 153: осталось пользователей 734
День 154: осталось пользователей 731
День 155: осталось пользователей 730
День 156: осталось пользователей 729
День 157: осталось пользователей 726
День 158: осталось пользователей 723
День 159: осталось пользователей 723
День 160: осталось пользователей 720
День 161: осталось пользователей 717
День 162: осталось пользователей 717
День 163: осталось пользователей 713
День 164: осталось пользователей 708
День 165: осталось пользователей 704
День 166: осталось пользователей 701
День 167: осталось пользователей 697
День 168: осталось пользователей 690
День 169: осталось пользователей 686
День 170: осталось пользователей 684
День 171: осталось пользователей 680
День 172: осталось пользователей 675
День 173: осталось пользователей 673
День 174: осталось пользователей 670
День 175: осталось пользователей 667
День 176: осталось пользователей 663
День 177: осталось пользователей 659
День 178: осталось пользователей 655
День 179: осталось пользователей 653
День 180: осталось пользователей 652
День 181: осталось пользователей 648
День 182: осталось пользователей 646
День 183: осталось пользователей 646
День 184: осталось пользователей 642
День 185: осталось пользователей 640
День 186: осталось пользователей 637
День 187: осталось пользователей 635
День 188: осталось пользователей 631
День 189: осталось пользователей 629
День 190: осталось пользователей 626
День 191: осталось пользователей 624
День 192: осталось пользователей 621
День 193: осталось пользователей 619
День 194: осталось пользователей 619
День 195: осталось пользователей 615
День 196: осталось пользователей 612
День 197: осталось пользователей 612
День 198: осталось пользователей 611
День 199: осталось пользователей 611
День 200: осталось пользователей 610
День 201: осталось пользователей 605
День 202: осталось пользователей 602
День 203: осталось пользователей 601
День 204: осталось пользователей 601
День 205: осталось пользователей 597
День 206: осталось пользователей 595
День 207: осталось пользователей 592
День 208: осталось пользователей 590
День 209: осталось пользователей 589
День 210: осталось пользователей 588
День 211: осталось пользователей 585
День 212: осталось пользователей 583
День 213: осталось пользователей 582
День 214: осталось пользователей 580
День 215: осталось пользователей 577
День 216: осталось пользователей 577
День 217: осталось пользователей 576
День 218: осталось пользователей 575
День 219: осталось пользователей 572
День 220: осталось пользователей 571
День 221: осталось пользователей 569
День 222: осталось пользователей 568
День 223: осталось пользователей 566
День 224: осталось пользователей 564
День 225: осталось пользователей 563
День 226: осталось пользователей 559
День 227: осталось пользователей 556
День 228: осталось пользователей 555
День 229: осталось пользователей 553
День 230: осталось пользователей 551
День 231: осталось пользователей 550
День 232: осталось пользователей 546
День 233: осталось пользователей 546
День 234: осталось пользователей 546
День 235: осталось пользователей 545
День 236: осталось пользователей 543
День 237: осталось пользователей 541
День 238: осталось пользователей 540
День 239: осталось пользователей 536
День 240: осталось пользователей 534
День 241: осталось пользователей 531
День 242: осталось пользователей 529
День 243: осталось пользователей 524
День 244: осталось пользователей 523
День 245: осталось пользователей 521
День 246: осталось пользователей 520
День 247: осталось пользователей 518
День 248: осталось пользователей 515
День 249: осталось пользователей 513
День 250: осталось пользователей 511
День 251: осталось пользователей 510
День 252: осталось пользователей 508
День 253: осталось пользователей 507
День 254: осталось пользователей 506
День 255: осталось пользователей 504
День 256: осталось пользователей 502
День 257: осталось пользователей 501
День 258: осталось пользователей 500
День 259: осталось пользователей 496
День 260: осталось пользователей 495
День 261: осталось пользователей 493
День 262: осталось пользователей 493
День 263: осталось пользователей 493
День 264: осталось пользователей 489
День 265: осталось пользователей 489
День 266: осталось пользователей 487
День 267: осталось пользователей 485
День 268: осталось пользователей 485
День 269: осталось пользователей 484
День 270: осталось пользователей 483
День 271: осталось пользователей 481

KeyboardInterrupt: